### ISSUE TITLE
Issue with \cite dropdown menu and new bibtex entries

### ISSUE THREAD

**Issue by fbragman** [SublimeText/LaTeXTools#1062]
I am running LaTexTools on Sublime3. It's worked perfectly fine until now.

I have two issues.

1) \cite dropdown menu with "cite_auto_trigger": true suddenly no longer works. The command \ref works fine and gives me a dropdown of all my labels.

When I try \cite{}, the terminal throws quite a lot of errors but the following seem the most pertinent:

> Traceback (most recent call last):
>   File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 326, in cache
>     return self.get(key)
>   File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 561, in get
>     return super(ValidatingCache, self).get(key)
>   File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 250, in get
>     result = self.load(key)
>   File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 384, in load
>     self._objects[key] = self._read(key)
>   File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 399, in _read
>     raise CacheMiss(u'cannot read cache file {0}'.format(key))
> LaTeXTools.latextools_utils.cache.CacheMiss: cannot read cache file bib_files

and 

> Traceback (most recent call last):`
>  File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 396, in _read
>     with open(file_path, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Cache/LaTeXTools/local_cache/87b22ccc0d113098225c8dbb0272a29c/bib_files'

2) If I set  "cite_auto_trigger": false in LaTexTools.sublime-settings, the \cite command works. However, the drop-down list now is in the format:

> #Doe2014
> #Doe2011

whilst before it was

> Doe2014
> Doe2011

Moreover, it won't list new entries I have added to my bib file from Mendeley. If I add the entries manually, the document compiles fine with the references. Otherwise, it won't automatically list them.

Thanks for any help. Happy to forward as much information as needed.

**Comment by r-stein** [comment]
DO you use the "new" or "traditional" bibliography?

**Comment by fbragman** [comment]
Thanks for the response.

I use the traditional_bibliography as the command and the traditional builder (I am on Linux).

I have never changed anything in the Bibliographic references section of the Settings file.

**Comment by r-stein** [comment]
Does it work with other bib files?

**Comment by r-stein** [comment]
Try to press ctrl+shift+p and select *LaTeXTools: Clear current bibliography cache* and try again

**Comment by fbragman** [comment]
I have deleted all auxiliary files and cleared the current bibliography cache. Still throwing errors.

I just ran a MWE with the same .bib file path I am using in the problem document and \cite works fine.

I think something is corrupted in this particular project since LaTexTools is working fine in two different examples.

This project has the following file hierarchy.

Project/main.tex --> includes all chapters
Project/chapter1/chapter1.tex

and within chapter1.txt --> %!TEX root = ../main.tex

**Comment by ig0774** [comment]
Could you try running the **LaTeXTools: Clear local file cache** command (Not sure of the exact name) with the problem document open?

**Comment by ig0774** [comment]
Also, how is the bibliography included in your document (i.e. `\bibliography` etc.)?

**Comment by fbragman** [comment]
Thanks for the super quick response.

I selected **LaTexTools: Clear document cache** since I do not get the option Clear local file cache. Still nothing.

I copied the entire project folder (Project --> Project_test), deleted all aux and tried from that one. Also not working.

But as detailed, \cite{} is working in different LaTex projects.

I include the bibliography in main.txt as: \bibliography{/scratch1/NOT_BACKED_UP/fbragman/bibtex/Research.bib}

**Comment by fbragman** [comment]
I've done some more investigating. It appears \cite drop-down is working correctly in single .tex file documents in the format:

> \begin{document}
This file is a test \cite{}.
\end{document}

However, in two different projects (which use the same thesis class file) of the format:

> main.txt
\begin{document}
\include{./file1/foo}
\end{document}

> foo.tex
\chapter{Example}
This file is a test \cite{}.

It doesn't work.

**Comment by r-stein** [comment]
If you press `{` or C-l, C-f there should be a message in the console

```
Bib files found: 
('path/to/research.bib',)
```

Does this show the correct file name?

**Comment by kop-legend** [comment]
Sorry to jump in -- just wanted to thank r-stein for the quick response as well. I had exactly the same problem, but it appears to have been fixed by clearing the various cache files. Sorry that this didn't work for you, fbragman, but greatly appreciate the help on here.

**Comment by fbragman** [comment]
When I press \cite{ and Ctrl+` to open the terminal, it throws a lot of errors, starting with:

> TEX root: '/scratch0/NOT_BACKED_UP/fbragman/Documents/thesis_git/main/main.tex'
Traceback (most recent call last):
  File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 556, in get
    self.validate_on_get(key)
  File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 684, in validate_on_get
    raise ValueError('value outdated')
ValueError: value outdated

and

> During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 326, in cache
    return self.get(key)
  File "/cs/research/medic/home2/paramedic/fbragman/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 559, in get
    raise CacheMiss(unicode(e))
LaTeXTools.latextools_utils.cache.CacheMiss: value outdated

**Comment by fbragman** [comment]
To touch on kop-legends post since they managed to solve their issue!

How can I be sure the cache is clearing properly or the other LaTexTools deletion commands? The terminal isn't listing anything so I am skeptical.

**Comment by r-stein** [comment]
Copy this in the ST console
```
import os; os.startfile(os.path.join(sublime.cache_path(), "LaTeXTools"))
```
This should open the cache folder.
Then close ST, delete the files inside that folder, and start ST again.

**Comment by fbragman** [comment]
Still not working :( I would start a new project and give up but it seems the problem is native to projects with the main and chapter format.

I am using Linux though so I used the following command:

`import sys, subprocess;
opener ="open" if sys.platform == "darwin" else "xdg-open";
subprocess.call([opener, os.path.join(sublime.cache_path(), "LaTeXTools")])`

**Comment by ig0774** [comment]
Is the `\bibliography` command in your main file or the included file?

**Comment by fbragman** [comment]
In the main file. And the chapter files all have: %!TEX root = ../main.tex at the top. If I put in an incorrect path e.g. %!TEX root = ../../main.tex, it says Bib file not found

Moreover, the cache folder only has two files: **analysis**  and **create_time_stamp**

I've realised projects where \cite works has three: **analysis**, **bib_files** and **create_time_stamp**

**Comment by r-stein** [comment]
You could try to clone the newest version from the master branch. I added something to improve the handling of bib-caching problems to be released in the next version.

**Comment by fbragman** [comment]
Okay! Thanks again - very appreciated.

Sorry for asking for so much help but what is the process for cloning the newest version? My only experience of using installing packages in sublime is via Package control

**Comment by r-stein** [comment]
Just select *Preferences > Browse Packages...* and delete the LaTeXTools folder. Then open a terminal there and write `git clone https://github.com/SublimeText/LaTeXTools` and restart ST.

**Comment by fbragman** [comment]
Thanks! Unfortunately, the error persists.

Thanks a lot for the troubleshooting. I am going to try deleting ST, re-installing it and set up LaTexTools again.

**Comment by r-stein** [comment]
Reinstalling ST won't help, because all cache files and installed plugins will stay where they are.

**Comment by r-stein** [comment]
Better try this: https://www.sublimetext.com/docs/3/revert.html

**Comment by fbragman** [comment]
Thanks. Unfortunately, even by reverting, reinstalling LaTexTools, it still doesn't work. I guess this is the way I will live from now.

**Comment by r-stein** [comment]
Unfortunately I can't reproduce the issue to fix it. If that bug is new you can also checkout an older version of LaTeXTools, by cloning it an then write inside the LaTeXTools folder `git checkout tags/v3.12.16`.

**Comment by sethblumberg** [comment]
I don't have any extra insight, but I can report that I encountered the same problem today: In a multi-file project, the bib file can't be found, but in single-file project, citations work properly.

**Comment by diego898** [comment]
Not sure if this related to #1055

**Comment by fbragman** [comment]
Well it appears I do get exactly the same problem i.e. \cite works in single-file projects but not multiple-files. But the errors I get do not reference not finding the bib file. I will try checking out a prior version.

**Comment by fbragman** [comment]
Okay so I checked out v3.12.15 and \cite{} drop-down in multiple file projects works.

It breaks as soon as I check into v3.13.0.

I am not entirely sure if this is a version-wide bug or just native to my workstation. Happy to further help figure out the issue. In any case, thanks a ton r-stein and ig-0774. LaTexTools is a hell of a project.

**Comment by r-stein** [comment]
In `v3.13` we changed things with the caches to improve the performance by moving stuff to other threads auch precalculate stuff. In addition the ref and cite commands are using the cached document analysis instead of scanning the commands on their own.

**Comment by BMorrisonUSyd** [comment]
I am having the same issue (on my Windows and Mac machine). The arrangement is similar, a multi tex file with (%!TEX root = ../main.tex) at top of the sub files. The file still compiles fine but the cite dropdown menu does not appear (and it can't find the bib according to the console output).

I also noticed that I could no longer \ref{} to labels outside of the file I am in, which wasn't the case of previous versions. I cleared the cache and the issue still occurred, dropping back to v3.12.16 and it works fine as before.

**Comment by ig0774** [comment]
Would someone be able to zip up a non-functioning document and email it? I can't reproduce the issue in my environments. I think there's something obvious that's being missed, but I can't tell what.

**Comment by alexeyza** [comment]
I've encountered this issue recently. `\ref` works, but `\cite` wouldn't show the menu. I tried other older latex files and it was the same for all of them. Clearing the document cache or bibliography cache didn't help.

```
TEX root: '/home/alexeyza/git/papers/ESEM2017/esem2017.tex'
Bib files found: 
['/home/alexeyza/git/papers/ESEM2017/references.bib']
Loaded 861 bibitems
Traceback (most recent call last):
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 397, in _read
    return pickle.load(f)
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/bibcache.py", line 55, in get
    return self.validate_on_get(result)
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/bibcache.py", line 108, in validate_on_get
    return self._get_bib_cache()[1]
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/bibcache.py", line 133, in _get_bib_cache
    bib_entries = self._read(self.cache_name)
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 399, in _read
    raise CacheMiss(u'cannot read cache file {0}'.format(key))
LaTeXTools.latextools_utils.cache.CacheMiss: cannot read cache file bib_new_b6acb2099599d6daf44d8134a4859e79

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 397, in _read
    return pickle.load(f)
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins/newBibliography.py", line 156, in get_entries
    fmt_entries = bib_cache.get()
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/bibcache.py", line 57, in get
    return self._get_bib_cache()[1]
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/bibcache.py", line 133, in _get_bib_cache
    bib_entries = self._read(self.cache_name)
  File "/home/alexeyza/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/cache.py", line 399, in _read
    raise CacheMiss(u'cannot read cache file {0}'.format(key))
LaTeXTools.latextools_utils.cache.CacheMiss: cannot read cache file bib_new_b6acb2099599d6daf44d8134a4859e79
Found 0 total bib entries
bib_entries must be pickleable
```
A temporary workaround I can see for now, is to switch to the `traditional_bibliography` option in the user settings.

**Comment by r-stein** [comment]
@alexeyza This is already fixed on the master, I will issue a new release now.

**Comment by BMorrisonUSyd** [comment]
So I tried to set up a MWE with my office windows machine. It never had latex tools installed so I installed the latest version and set up a fresh template (I am using the theses template from [here](https://www.latextemplates.com/template/masters-doctoral-thesis)).

And the issue didn't occur... The relative file structure of my actual document is a little different (with nested chapter folders). I messed around with that on my mac laptop and the \cite{} dropdown still did not appear (back on the latest version). However the /ref now worked correctly so that issue was likely caused by my relative path definitions.

I will repeat the fresh template above on my home windows machine and see if the issue still occurs and email a proper MWE. Cheers

**Comment by alexander-e** [comment]
It seems like I have an even bigger malfunction. The \cite dropdown menu does not show in a latex document with multiple \input files, but also not in a single document. I am currently on v3.13.4, ST3 Build 3126, Ubuntu 16.04. If I recall correctly, the \cite command worked just fine one or two versions of LaTeXTools ago...
PS: This is the first bug that I have encountered. Thanks for all the hard work you guys put into this package, its awesome!

**Comment by brunodigiorgi** [comment]
Hi, just wanted to report that I'm having the same issue in a multi-file project. \ref{} is working but not \cite{}. main.tex is referenced as absolute path in the .sublime-project file. \cite{} is not working in main.tex either.

The exceptions from the console are pasted here 
[https://pastebin.com/pV0rfDk6](https://pastebin.com/pV0rfDk6)

**Comment by r-stein** [comment]
@brunodigiorgi Thanks thas usefull. Do you have something like `\bibliography` or `\nobibliography` without arguments in your tex file?

**Comment by fbragman** [comment]
Hey,

Since I start this, I thought I may upload an mwe as per request.

I have uploaded a zip file, inside there is:

> ./Main.tex --> the main file for the dummy project
./chapter1/Chapter1.tex --> example for multi-file project --> this is where I call \cite
./IPMI.bib --> example bib file with some references
./ucl_thesis.cls --> thesis class I am using
MainPackages.tex / LinksAndMetadata.tex / FloatSettings.tex / BibSettings.tex --> parameters for thesis

The \cite dropdown works on v3.12.15 for me with this but does not for v3.13+

I am running Linux CentOS 6.8 (Carbon) with SublimeText 3.

[mwe.zip](https://github.com/SublimeText/LaTeXTools/files/885175/mwe.zip)

**Comment by r-stein** [comment]
@fbragman That also seems to be the issue with you. I am going to fix that and cut a release.

**Comment by brunodigiorgi** [comment]
These are the commands in my main ("thesis.tex"):
    
    \bibliographystyle{ieeetr}
    \bibliography{thesis}

Bibliography file is named "thesis.bib". I have a \nobibliography* command before \begin{document}. Removing that does not seem to help.

**Comment by r-stein** [comment]
if you remove that and then press C-l, backspace or C-l, C-d, C-c does that help?

**Comment by brunodigiorgi** [comment]
Yes! Solved 👍 
Thank you very much.

**Comment by r-stein** [comment]
I have released a new version `v3.13.5`, which should fix that problem. Let me know if you still have this issue after the update.

**Comment by alexander-e** [comment]
The update works for me, the \cite dropdown menu shows up and works as before. :) Thanks for the quick fix!

**Comment by brunodigiorgi** [comment]
No issue after the update. I can use \nobibliography*, and the \cite menu works without problems

**Comment by renbem** [comment]
Thanks a lot for the prompt fix!

**Comment by BMorrisonUSyd** [comment]
Yep, the issue is solved for me too, I think that sorted it.

And like I mentioned briefly before, I think the /ref{} issue I was having was due to the relative paths I had defined everywhere for my different chapters. This was a requirement when I was using the Subfiles package, before I shifted to the main text usage with LaTeXTools.

I just want to say that this really is an amazing tool and I could not imagine a big chunk of my PhD progressing the way it has without it, its one of the first things I recommend to anyone when learning about LaTeX. Cheers!

**Comment by diego898** [comment]
After clearning all caches, deleting all temp files, restarting sublime, in a multi project file when I first issue `\cite`, I still get "no bib files found". I then press ok, and do it again and the dropdown appears as expected and everything is normal

**Comment by r-stein** [comment]
Thanks for the positive feedback =) I will close this issue then.

@diego898 This also sometimes occured for me, but I can't reproduce it reliable. You can create a new issue for that.

**Comment by sethblumberg** [comment]
The `v3.13.5` update at first didn't fix the problem for me, but I was able to figure out why.  Here is  a situation where LaTeXTools' cite-completion still fails:

If the `\bibliography{…}` command is the argument of a function, LaTeXTools fails to find the bib file.

In my case, I called the bibliography with the line

    \small{\bibliography{../bibliographies/bigbib}}

but after I changed it to 

	{\small\bibliography{../bibliographies/bigbib}}

it worked fine.  The first was wrong syntax anyhow, but a situation where it would be right is `\textsc{\bibliography{…}}`, which turns all plain-formatted text of the bibliography into smallcaps.

Another construct I use that puts the bibliography inside of another command is [this trick](http://tex.stackexchange.com/a/31378/30594) to compile cites but not print a bibliography section.  It involves creating a savebox with the bibliography inside it.  In this case, too, LaTeXTools didn't figure out the bib file for cite completions.
