### ISSUE TITLE
ST4 not invoking PDF viewer on macOS?

### ISSUE THREAD

**Issue by hhergert** [SublimeText/LaTeXTools#1539]
After updating to ST4 (build 4113), the builder does not launch the PDF viewer (Skim) any more. (MacOS 10.14.6 Mojave, Skim 1.6.4). I tried changing the viewer commands in LaTeXTools.sublime-settings, but it seems that viewer-related commands are simply ignored. latexmk etc. seem to work fine, as does \cite resolution etc., and I can use the settings file to toggle output of logs in the console, for example.

**Comment by hhergert** [comment]
Following up: I fixed some tabs and spaces in jumpToPDF.py (lines 100ff.) that were flagged as inconsistent in debug mode and changed the permissions of the displayfile script in the skim subfolder to make it executable - either the fixed indents or the combination of the two seems to have done the trick (I changed the permissions earlier, so that alone was not it). Skim is starting and syncing to the proper lines again.

**Comment by hadisfr** [comment]
Reproduced in Ubuntu, too.

**Comment by bipson** [comment]
Encountered the same issue on Linux in master or the latest release (st3-4.0.0-beta.0 tag seems to still work, but using tags is not a sustainable solution for me with SublimeText).

PR #1540 seems to fix it for me. Please consider merging it.

**Comment by itsrainingdata** [comment]
I've been encountering the same issue for several months. Have tried uninstalling and re-installing Skim, and found the problem persisted over versions 1.67, 1.6.8, 1.6.10. Mac OS Monterey 12.0.1.

See also https://tex.stackexchange.com/questions/618983/pdf-viewer-skim-not-opening-or-updating-on-build-with-sublime-text-4-and-latex

**Comment by Kamik423** [comment]
This needs to be fixed. Please accept the PR.

**Comment by deathaxe** [comment]
Fixed by 3b66aea49eed010b2e098fcb999a696fedbf88aa.
