### ISSUE TITLE
delete_temp_files ignores `*.foo.bar` filenames

### ISSUE THREAD

**Issue by mcnesium** [SublimeText/LaTeXTools#517]
In #516 I added some more filetypes to be deleted by [delete_temp_files.py](https://github.com/SublimeText/LaTeXTools/blob/master/delete_temp_files.py#L28). However, both `.run.xml`, and `.synctex.gz` seem to have no effect, both files in my project are not being deleted by the script.

**Comment by xacid** [comment]
os.path.splitext gives only the '.bar' in its output.
Seems file_name.endswith(ext) works.
http://stackoverflow.com/questions/541390/extracting-extension-from-filename-in-python

**Comment by ig0774** [comment]
Incidentally, this is fixed in #494. Presumably when @msiniscalchi gets a chance, that'll and a couple of other bugfixes will get merged into the main tree.

**Comment by juanfal** [comment]
Last version (just installed) has the very same code here as before, no fixes:

file **delete_temp_files.py**:28-37

		temp_exts = set(['.blg','.bbl','.aux','.log','.brf','.nlo','.out','.dvi','.ps',
			'.lof','.toc','.fls','.fdb_latexmk','.pdfsync','.synctex.gz','.ind','.ilg','.idx'])

		for dir_path, dir_names, file_names in os.walk(self.path):
			for file_name in file_names:
				file_base, file_ext = os.path.splitext(file_name)
				if file_ext in temp_exts:
					file_name_to_del = os.path.join(dir_path, file_name)
					if os.path.exists(file_name_to_del):
						os.remove(file_name_to_del)

This code has a clear bug.  If you want to find files the *extension* `'.synctex.gz'` you shouldn't use `os.path.splitext()` since it always takes the last ext.  You should use `string.endswith(temp_ext…)`

**Comment by juanfal** [comment]
I am not a pythonist at all.  I have substituted the existing code by the next one (simpler) and it works for me:


    class Delete_temp_filesCommand(sublime_plugin.WindowCommand):
        def run(self):
            # Retrieve file and dirname.
            view = self.window.active_view()
            self.file_name = getTeXRoot.get_tex_root(view)
            if not os.path.isfile(self.file_name):
                sublime.error_message(self.file_name + ": file not found.")
                return

            self.path = os.path.dirname(self.file_name)
            file_base, file_ext = os.path.splitext(self.file_name)

            # Delete the files.
            temp_exts = set(['.blg','.bbl','.aux','.log','.brf','.nlo','.out','.dvi','.ps',
                '.lof','.toc','.fls','.fdb_latexmk','.pdfsync','.synctex.gz','.ind','.ilg','.idx'])


            cnt = 0
            for ext in temp_exts:
                trying = file_base + ext
                if os.path.exists(trying):
                    os.remove(trying)
                    cnt += 1

            sublime.status_message("Deleted " + str(cnt) + " temp files")

**Comment by msiniscalchi** [comment]
Indeed this was not fixed... I'll take a look. Sorry!

On Sun, Nov 15, 2015 at 12:51 PM, juanfal <notifications@github.com> wrote:

> I am not a pythonist at all. I have substituted the existing code by the
> next one (simpler) and it works for me:
>
> class Delete_temp_filesCommand(sublime_plugin.WindowCommand):
>     def run(self):
>         # Retrieve file and dirname.
>         view = self.window.active_view()
>         self.file_name = getTeXRoot.get_tex_root(view)
>         if not os.path.isfile(self.file_name):
>             sublime.error_message(self.file_name + ": file not found.")
>             return
>
>         self.path = os.path.dirname(self.file_name)
>         file_base, file_ext = os.path.splitext(self.file_name)
>
>         # Delete the files.
>         temp_exts = set(['.blg','.bbl','.aux','.log','.brf','.nlo','.out','.dvi','.ps',
>             '.lof','.toc','.fls','.fdb_latexmk','.pdfsync','.synctex.gz','.ind','.ilg','.idx'])
>
>
>         cnt = 0
>         for ext in temp_exts:
>             trying = file_base + ext
>             if os.path.exists(trying):
>                 os.remove(trying)
>                 cnt += 1
>
>         sublime.status_message("Deleted " + str(cnt) + " temp files")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/517#issuecomment-156842936>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by ig0774** [comment]
#520 was merged which also addressed this issue.
