### ISSUE TITLE
Recent release broke citation search if citation has duplicates (which worked on <3.7.0)

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#686]
I don't know what piece of the recent release did this, but now when I type `\cite{` nothing happens. 

I checked and its not that the popup interface in general is broken because `\autoref{` still works.

To clarify further; it does seem to be triggering something as there is a slight (300–500 ms?) lag before the color changes during which the window would usually pop up. 

It is finding the bibliography or at least it says so in the console; it seems to have some issue with chomping through keys that it didn't use to have.

```
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 743, in run
    completions, prefix, post_brace, new_point_a, new_point_b = get_cite_completions(view, point)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 656, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 414, in run_plugin_command
    result = _run_command(plugin_name)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 375, in _run_command
    result = getattr(plugin, command)(*args, **kwargs)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/traditionalBibliography.py", line 105, in get_entries
    bib_data = parser.parse(bibf.read())
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/parser.py", line 100, in parse
    database.add_entry(entry)
  File "~/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/model.py", line 53, in add_entry
    entry.cite_key
KeyError: 'entry with key lagnados2010 already exists'

```

**Comment by r-stein** [comment]
The bibliography now does parse the bibtex and it seems you have defined the key `lagnados2010` in more than one entry. I think it would be useful to make the parser more error resistant, but you could look in your bibfile, whether you have defined that key twice.

**Comment by michaelpacer** [comment]
Just checked, and yep, I did define that twice. And until today it was more error resistant because I've been using this `bib` file + LaTeXtools without issue for a while now.

**Comment by r-stein** [comment]
Until now it was more like a heuristic search, now it uses a real parser.

**Comment by ig0774** [comment]
@michaelpacer Sorry about the breakage. I wasn't quite sure what the behaviour was with duplicate entry keys. It looks like bibtex / biber / et al. just keep the first entry encountered and ignore any duplicates. I've modified the parser and will try to get a new release together shortly. Thanks for the error report.

**Comment by michaelpacer** [comment]
Happy to help. Once I'm done writing my diss, I'm excited to figure out how to contribute back. 

Also now that its actually parsing the file, I think there's a couple of straightforward enhancements I'll open separate issues for.

This project has been phenomenally helpful. Thanks a bunch.

**Comment by sdruskat** [comment]
I get the same behaviour (when I type `\cite{` nothing happens) on Ubuntu 14.04 with ST3. I've checked, and there are no duplicate keys in the .bib file.

**Comment by r-stein** [comment]
Please open your console ``ctrl+` `` or `View >>> Show Console` and look at the output while pressing `{`.

**Comment by sdruskat** [comment]
This is the stack trace.

    545
    True True
    Dispatching cite
    546
    TEX root: '/home/me/document/document.tex'
    Searching file: '/home/me/document/document.tex'
    Bib files found: 
    ['/home/me/document/references.bib']
    Files:
    ['/home/me/document/references.bib']
    Traceback (most recent call last):
      File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
        return self.run(edit)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 743, in run
        completions, prefix, post_brace, new_point_a, new_point_b = get_cite_completions(view, point)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 656, in get_cite_completions
        completions = run_plugin_command('get_entries', *bib_files)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 414, in run_plugin_command
        result = _run_command(plugin_name)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 375, in _run_command
        result = getattr(plugin, command)(*args, **kwargs)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins/traditionalBibliography.py", line 105, in get_entries
        bib_data = parser.parse(bibf.read())
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins/bibtex/parser.py", line 57, in parse
        self.tokens = self.lexer.tokenize(s)
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins/bibtex/lexer.py", line 88, in tokenize
        self.token_error()
      File "/home/me/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins/bibtex/lexer.py", line 289, in token_error
        self.code[self.current_index:].split('\n', 1)[0]
    SyntaxError: 231:3 - unrecognised token "__markedentry            = {[me:6]},"

.bib file is straight out of JabRef.

**Comment by ig0774** [comment]
@sdruskat: Ah. I hadn't realized JabRef uses fields like that. It's easy enough to support, and a fix will be released soon (its pushed to `master`; I've got a few small things I want to deal with as well before a new release).

**Comment by xiaoweiz** [comment]
I encountered a similar problem but with different error message. I've using LatexTools for a couple of years and never had this problem. 

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 827, in run
    for completion in completions], on_done)
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 827, in <listcomp>
    for completion in completions], on_done)
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 826, in <listcomp>
    view.window().show_quick_panel([[formatter.vformat(s, (), completion) for s in cite_panel_format] \
  File "./string.py", line 168, in vformat
  File "./string.py", line 190, in _vformat
  File "./string.py", line 253, in get_field
  File "./string.py", line 210, in get_value
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 465, in __getitem__
    return self._entry[key]
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/traditionalBibliography.py", line 76, in __getitem__
    people = [Name(x) for x in tokenize_list(self.entry[key])]
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/traditionalBibliography.py", line 76, in <listcomp>
    people = [Name(x) for x in tokenize_list(self.entry[key])]
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/names.py", line 170, in __init__
    tokenize_name(name_str)
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/names.py", line 88, in tokenize_name
    forenames[0],
IndexError: list index out of range
```

**Comment by ig0774** [comment]
@sdruskat: Your issue should be resolved in [v3.7.3](https://github.com/SublimeText/LaTeXTools/releases/tag/v3.7.3)

@xiaoweiz: New code, new bugs... I've added a shim that should work around your issue, but I can't determine the underlying cause. v3.7.3 will basically just swallow the error and report it to the console. If you can update and try it out and let me know what it report (there should be a line before the stack trace), I'll see if I can't figure out what's actually broken.

**Comment by sdruskat** [comment]
@ig0774: Brilliant, thanks very much! Great turnaround, great project! My professional life actually depends on you :).

**Comment by xiaoweiz** [comment]
@ig0774 Thanks a lot for the quick fix. It now works. 

The issue was caused by an error in my bib file. There were a couple of entries whose "author" field had two "and" between two author names, such as John Doe _and and_ Jane Doe. The error message of LatexTools is something like 
```python
Error handling field "author" with value "and John Davies"
Traceback (most recent call last):
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/traditionalBibliography.py", line 82, in __getitem__
    people.append(Name(x))
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/names.py", line 170, in __init__
    tokenize_name(name_str)
  File "/Users/xiaoweiz/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/bibtex/names.py", line 88, in tokenize_name
    forenames[0],
IndexError: list index out of range
latex_cite_completion called with index -1
```

**Comment by simonstu** [comment]
I have a similar problem, however, the error message in the console does not really help which bib-entry I should fix. Any ideas? The .bib file is also straight out of JabRef. Thanks!

```
Bib files found: 
['C:\\Users\\simon\\Dropbox\\diss\\thesis\\latex\\bibliography.bib']
Files:
['C:\\Users\\simon\\Dropbox\\diss\\thesis\\latex\\bibliography.bib']
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 743, in run
    completions, prefix, post_brace, new_point_a, new_point_b = get_cite_completions(view, point)
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 656, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 414, in run_plugin_command
    result = _run_command(plugin_name)
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 375, in _run_command
    result = getattr(plugin, command)(*args, **kwargs)
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\traditionalBibliography.py", line 134, in get_entries
    bib_data = parser.parse(bibf.read())
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 86, in parse
    entry_node = self.entry()
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 192, in entry
    node.fields = self.key_values()
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 246, in key_values
    node.value = self.field_value()
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 256, in field_value
    return self.concatenated_value() or self.value()
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 306, in value
    self.unexpected_token('quoted_string, value, identifier, or number')
  File "C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\bibtex\parser.py", line 333, in unexpected_token
    expecting
SyntaxError: 2185:4 - unexpected key; expecting quoted_string, value, identifier, or number

```

**Comment by HansH** [comment]
The \cite dropdown is still not working for me. This is the error I'm getting:
```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\latex_cite_completions.py", line 743, in run
  File ".\latex_cite_completions.py", line 656, in get_cite_completions
  File ".\latex_cite_completions.py", line 414, in run_plugin_command
  File ".\latex_cite_completions.py", line 375, in _run_command
  File ".\bibliography_plugins\traditionalBibliography.py", line 134, in get_entries
  File ".\bibliography_plugins\bibtex\parser.py", line 57, in parse
  File ".\bibliography_plugins\bibtex\lexer.py", line 88, in tokenize
  File ".\bibliography_plugins\bibtex\lexer.py", line 289, in token_error
SyntaxError: 275:43 - unrecognised token "cpp-sp-ext.git},"
```
The bib entry containing "cpp-sp-ext.git" is this one:
```
@misc{cppSpExt,
  title={{cpp-sp-ext}},
  url={https://git.shibboleth.net/view/?p=cpp-sp-ext.git},
  howpublished={Git repository, revision 48a907140e04788a3e68f4efcdff34ce6ae0b334},
  year={2011},
  month={11},
  day={16},
  author={Cantor, Scott}
}
```

**Comment by cod3licious** [comment]
Since the last few updates, the `\cite{` autocomplete doesn't work anymore. I just got updated to 3.7.7 but it's still not fixed. I reset my LaTexTools.sublime-settings but nothing helps. This is the output from the console:
```
True True
Dispatching cite
940
TEX root: u'/Users/franzi/Documents/uni zeugs/Promotion/project_plan/year_one/year1.tex'
Searching file: u'/Users/franzi/Documents/uni zeugs/Promotion/project_plan/year_one/year1.tex'
Bib files found: 
[u'/Users/franzi/Documents/uni zeugs/Promotion/papers/phd_collected.bib']
Files:
[u'/Users/franzi/Documents/uni zeugs/Promotion/papers/phd_collected.bib']
Could not find bibliography plugin named t. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named r. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named d. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named t. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named o. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named n. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named l. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named _. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named b. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named b. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named l. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named o. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named g. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named r. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named p. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named h. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named y. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 743, in run
  File "./latex_cite_completions.py", line 656, in get_cite_completions
  File "./latex_cite_completions.py", line 421, in run_plugin_command
latex_cite_completions.BibPluginError: Could not find a plugin to handle 'get_entries'. See the console for more details```

It seems like this should be an easy fix but I'm not familiar with the package...

**Comment by r-stein** [comment]
@cod3licious can you try to add `bibliography": ["traditional_bibliography"],` to your settings?
@ig0774 in line `406` of `latex_cite_completions.py` the default plugins should be an array

**Comment by ig0774** [comment]
@cod3licious: v3.7.8 fixes this
