### ISSUE TITLE
LaTeXtools could not parse the TeX log file (actually, we never should have gotten here)

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeText/LaTeXTools#746]
Trying to compile my .tex file, I get the following error

```
TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.


LaTeXtools could not parse the TeX log file
(actually, we never should have gotten here)

Python exception: ValueError('need more than 2 values to unpack',)

Please let me know on GitHub. Thanks!
```

I'm running Sublime 3 (3114), on Linux Mint 17 (2.2.16, 64-bit). This same .tex file compiles with no issues on my other system (elementary OS Freya, based on Ubuntu 14.04, 64-bit)

I attach the log file as file_log.txt, let me know of anything else you need to debug this.

[file_log.txt](https://github.com/SublimeText/LaTeXTools/files/303343/file_log.txt)

**Comment by Gabriel-p** [comment]
The `! LaTeX Error: File `newtxtext.sty' not found` issue is related to the `newtxtext,newtxmath` packages (see http://tex.stackexchange.com/questions/251405/problem-with-new-mnras-style-files-newtx-on-arxiv#)

I tried commenting these to out but the problem remains.

**Comment by ig0774** [comment]
This seems connected to #714. Thanks for the log file it should be helpful in tracking this down.

**Comment by ig0774** [comment]
One other question: do you use Sublime less frequently on the system where this error occurred?

One possible explanation of this ghost issue is that an old version of the log parsing code somehow remains cached in memory while the rest of the plugin code is updated. If that's the case, the issue might've been resolved by simply restarting ST.

**Comment by Gabriel-p** [comment]
Indeed, this error occurred in system that I very seldom use. If by restarting ST you mean simply a close/open cycle, that did not resolve the issue in my case.

**Comment by corneruestc** [comment]
TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.


LaTeXTools could not parse the TeX log file /Users/.../Ex_on_Net_V7_Xu_08010.log
(actually, we never should have gotten here)

Python exception: TypeError('parse_tex_log() takes 1 positional argument but 2 were given',)

The full error description can be found on the console.
Please let us know on GitHub. Thanks!

[Done!]

**Comment by ig0774** [comment]
@corneruestc: That's a somewhat different issue, hence the different message. Nonetheless, it shouldn't've occurred. Can you pull any messages from the console (**View | Console**)?

**Comment by corneruestc** [comment]
Yes, here are two of the messages:
_message1:_
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-79
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', 'Ex_on_Net_V7_Xu_08010.tex']
Finished normally
0
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 289, in run
    data, self.caller.tex_dir
TypeError: parse_tex_log() takes 1 positional argument but 2 were given
False True True
Jump to:  288 383
<class '_latextools_skim_viewer.SkimViewer'>

_message2:_
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-80
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', 'Ex_on_Net_V7_Xu_08010.tex']
Finished normally
0
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 289, in run
    data, self.caller.tex_dir
TypeError: parse_tex_log() takes 1 positional argument but 2 were given
False True True
Jump to:  281 126
<class '_latextools_skim_viewer.SkimViewer'>

**Comment by ig0774** [comment]
@corneruestc: That's actually the same issue as #802 which should've been resolved in v3.10.5. In any case, quitting and then relaunching ST should resolve the issue.
