### ISSUE TITLE
SumatraPDF crashes with pdf formed by build in Sublime Text 3

### ISSUE THREAD

**Issue by HughParsonage** [SublimeText/LaTeXTools#937]
I am experiencing a persistent problem in Windows where Sumatra will start `Not responding` or `Please wait, rendering` when opening a PDF produced by `Ctrl + B` in Sublime Text 3. It does not occur when I run pdflatex from the command line and I believe only occurred in a recent update to Sublime Text 3 (possibly the last month). I have reproduced this problem on two computers, and both occurred at the time of a recent update.

**Comment by ig0774** [comment]
Is it possible to upload a document that reproduces this behaviour?

**Comment by HughParsonage** [comment]
It occurs on a simple `Hello world!` `.tex` file.

**Comment by ig0774** [comment]
Which version of Sumatra are you using?

**Comment by HughParsonage** [comment]
v3.1.1, git commit `5d317fd`

**Comment by JorgeGT** [comment]
I've noticed the same problem after a recent update, both with SumatraPDF and Evince, but I haven't found a way to consistently reproduce the issue. After a crash, the same document works correctly for a while. I will update if I find something.

**Comment by r-stein** [comment]
Does it also crash if you open SumatraPDF manually or only if you open it from Sublime Text?

**Comment by JorgeGT** [comment]
Each time I manually opened Sumatra/Evince it worked without issue, but after the document was updated a few times from compiling with Sublime, Sumatra/Evince would crash, even if the Sumatra/Evince instance was opened manually.

However I think it has been a few days since this last happened, so maybe some update fixed it (so far this morning hasn't happened, at least). Any diagnostics/info you would need if I get one of these crashes?

**Comment by kiwitea** [comment]
Same issue started occurring on my machine as well, since perhaps a week or two.
Typically happens around the 5th time I build a document, but I can't reliably reproduce it.
I'm using the "traditional" Latex Builder with pdflatex.

I'm on Windows 8.1, ST3 3126, Sumatra 3.1.2 64bit

**Comment by jutongpan** [comment]
The same situation as kiwitea. Sumatra does not crash until I build the document a few times.

**Comment by h2li** [comment]
Same situation on Windows 7 Enterprise SP1 + ST3 3126 + SumatraPDF 3.1.2 64bit. I tried to reinstall SumatraPDF but the issue still persists.

**Comment by Mario1988** [comment]
Same situation on Fedora 20 with Mate 1.8.2 and Evince 3.10.2 and on Windows 10 with SumatraPDF 3.1.2 64bit.

**Comment by HughParsonage** [comment]
I find that closing Sublime Text 3 immediately unfreezes SumatraPDF.

**Comment by ig0774** [comment]
@HughParsonage: Thanks! That's a helpful observation... I haven't been able to reproduce the issue in my environment yet, but perhaps there's some circumstance where the processes we use to communicate with Sumatra are hanging.

**Comment by ig0774** [comment]
Could someone please try disabling the **Automatically check for updates** feature in SumatraPDF and see if that resolves the issue? I suspect that there might be a timing issue between Sumatra's re-rendering and LaTeXTools sending the "open this file at this position" message.

**Comment by HughParsonage** [comment]
I experience the problem even when **Automatically check for updates** is unchecked.

**Comment by pravin-endeavour** [comment]
Yep, I experience this problem. Ever since I updated Sublime text.

**Comment by hsiaoyi0504** [comment]
Same issue ++

**Comment by cnasikas** [comment]
+1

**Comment by thanaset** [comment]
I also have the same problem.

**Comment by JSlote** [comment]
Yes, me as well

**Comment by alexiskattan** [comment]
When I open Sumatra on my own it seems to work.

**Comment by skimmel** [comment]
I have the same issue.

**Comment by r-stein** [comment]
You can set [`open_pdf_on_build`](https://github.com/SublimeText/LaTeXTools/blob/v3.12.11/LaTeXTools.sublime-settings#L510) to `false` and manually jump via C-l, j.
If someone has an idea to fix this it would be nice if he provides it.

**Comment by ig0774** [comment]
[This gist](https://gist.githubusercontent.com/ig0774/2a69aa06e58651df87274c6e8d11faff/raw/17b48470b3abb8a65a31449a2d0a2ddffb1f6a73/sumatra_viewer.py) may possibly fix things or at least restore the launching behaviour to how it was prior to 123bafe. 

 Since I'm having difficulty reproducing the issue, I need someone who is actually experiencing this issue to test it. To test this:

1. Please download the [linked file](https://gist.githubusercontent.com/ig0774/2a69aa06e58651df87274c6e8d11faff/raw/17b48470b3abb8a65a31449a2d0a2ddffb1f6a73/sumatra_viewer.py) and save it somewhere as `sumatra_viewer.py`.
1. In Sublime Text, from the Command Palette (`C-shift-p`), run **Preferences: Browse Packages**.
1. Find and open the `LaTeXTools` folder and then the `viewers` folder.
1. Copy the `sumatra_viewer.py` file downloaded above replacing the existing `sumatra_viewer.py` folder.
1. Quit and restart ST

Please report back if this fixes things for you or if the problem persists.

Finally, we appreciate that this is an actual issue that many people are experiencing but adding "+1" or "I have this issue, too" comments is not terribly helpful and can actually make it harder to find relevant information about the issue. If you'd like to express that you are experiencing the same issue, please use the [Github reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature. To subscribe to this issue to be kept aware of updates, please use [Github's built-in feature for this](https://help.github.com/articles/subscribing-to-conversations/). That way we're not spamming everyone. Thanks!

**Comment by HughParsonage** [comment]
@ig0774  That seems to work. After a few days of recompiling the same document, I did not encounter the problem after several rebuilds.

**Comment by cnasikas** [comment]
@ig0774 I did the test. I am working several days with different documents / projects without any issue so far.

**Comment by ig0774** [comment]
Thanks @HughParsonage and @cnasikas. I'll try to get a fix together and released in the next couple of days.

**Comment by HughParsonage** [comment]
Should I revert the `sumatra_viewer.py` in the meantime, or will the release overwrite that patch?

**Comment by r-stein** [comment]
Just keep the change, i t will be overwritten by the release.

**Comment by ig0774** [comment]
@pravin-endeavour: What version of Sumatra are you using? Did you quit and restart ST after downloading the updated `sumatra_viewer.py` file?

**Comment by ig0774** [comment]
v3.12.12 applies the fix that seems to work for most people. This may also fix the issue reported with Evince, assuming it has a similar root cause (I also haven't been able to reproduce this issue on my Linux box with Evince, so I'll need some feedback from someone experiencing the issue there).

For now, I'm regarding the underlying issue of the initial report to have been resolved. Further similar issues should ideally be tracked as separate issues so they don't lose visibility.

**Comment by ig0774** [comment]
@pravin-endeavour: Re-looking at the gist, I think the problem might be that I didn't apply the fix when Sumatra has to be found via the `_find_sumatra_exe()` method, i.e., when Sumatra is *not* available on the `PATH` or via the `sumatra` setting, but is detected via the registry or the default installation paths. This is because the gist was just a quick mock-up to test an idea for resolving a problem I couldn't reproduce. The actual committed fix covers both instances.

**Comment by JorgeGT** [comment]
@ig0774 Certainly it seems very hard to reproduce the issue with Evince, it has happened to me but very sparsely now. I will make sure to report if it happens again after I update to v3.12.12.

**Comment by pravin-endeavour** [comment]
Yes the issue still persists with the latest update to LatexTools (running latest versions of Sublime text and Sumatra).
